# Generated by Django 5.1.4 on 2024-12-12 07:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Aplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('photo_file', models.ImageField(upload_to='photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])], verbose_name='Фото')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('done', 'Выполнено'), ('haired', 'Принято в работу')], default='new', max_length=250, verbose_name='Статус')),
                ('comment', models.CharField(blank=True, max_length=250, verbose_name='Комментарий')),
                ('photo_file2', models.ImageField(upload_to='photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])], verbose_name='Фото готовой заявки')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category', verbose_name='Категория')),
            ],
        ),
    ]
