# Generated by Django 5.1.4 on 2024-12-13 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplication',
            name='photo_file3',
            field=models.ImageField(default='def', upload_to='photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])], verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aplication',
            name='photo_file4',
            field=models.ImageField(default='lol', upload_to='photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])], verbose_name='Фото готовой заявки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aplication',
            name='photo_file2',
            field=models.ImageField(upload_to='photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])], verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
