# Generated by Django 5.1.4 on 2024-12-13 13:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_aplication_photo_file3_aplication_photo_file4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplication',
            name='photo_file3',
        ),
        migrations.RemoveField(
            model_name='aplication',
            name='photo_file4',
        ),
        migrations.AlterField(
            model_name='aplication',
            name='photo_file2',
            field=models.ImageField(upload_to='photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])], verbose_name='Фото готовой заявки'),
        ),
        migrations.CreateModel(
            name='ApplicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='application_images/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.aplication')),
            ],
        ),
    ]
