# Generated by Django 5.1.4 on 2024-12-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_aplication_photo_file3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationImage',
        ),
    ]
