# Generated by Django 5.1.4 on 2024-12-16 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_applicationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplication',
            name='photo_file3',
            field=models.ImageField(blank=True, upload_to='photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])], verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='aplication',
            name='photo_fileReady',
            field=models.ImageField(default='lol', upload_to='photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])], verbose_name='Фото готовой заявки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aplication',
            name='photo_file',
            field=models.ImageField(upload_to='photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])], verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='aplication',
            name='photo_file2',
            field=models.ImageField(blank=True, upload_to='photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])], verbose_name='Фото 2'),
        ),
    ]
