# Generated by Django 3.2.25 on 2024-12-18 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_aplication_photo_file3_aplication_photo_fileready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplication',
            name='photo_fileReady2',
            field=models.ImageField(blank=True, upload_to='photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])], verbose_name='Фото готовой заявки'),
        ),
        migrations.AddField(
            model_name='aplication',
            name='photo_fileReady3',
            field=models.ImageField(blank=True, upload_to='photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])], verbose_name='Фото готовой заявки'),
        ),
        migrations.AlterField(
            model_name='aplication',
            name='photo_file',
            field=models.ImageField(blank=True, upload_to='photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])], verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='aplication',
            name='photo_fileReady',
            field=models.ImageField(blank=True, upload_to='photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])], verbose_name='Фото готовой заявки'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
    ]
